# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gh_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='feature', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='shelter',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shelter',
            name='name',
            field=models.CharField(default='shelter', max_length=20),
        ),
        migrations.AddField(
            model_name='shelter',
            name='num_guests',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shelter',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='person',
            name='ssn',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shelter',
            name='features',
            field=models.ManyToManyField(to='gh_app.Feature'),
        ),
    ]
