# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gh_app', '0002_auto_20161022_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ssn',
            field=models.PositiveIntegerField(default=0, verbose_name='SSN'),
        ),
    ]
