# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gh_app', '0003_auto_20161022_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='num_guests',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Number of current guests'),
        ),
    ]
