# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gh_app', '0005_auto_20161022_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='google_place_id',
            field=models.CharField(default='id', max_length=30),
        ),
    ]
